### ISSUE TITLE
yaml syntax highlighting not rendering

### ISSUE THREAD

**Issue by rlh1994** [snowplow/documentation#148]
When a code block specifies a `yaml` language tag these are not rendered out correctly on the published site despite being a supported prism default language. It fails both with `yml` and `yaml` as the language names.

Example:
https://docs.snowplow.io/docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/#model-configuration
https://github.com/snowplow/documentation/blob/6c3dec2c09f14372c3b0b7c8be64337085f01632/docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/index.md?plain=1#L145-L155

**Comment by stanch** [comment]
Have you tried adding it here? https://github.com/snowplow/documentation/blob/main/docusaurus.config.js#L125
Not all prism-supported languages are enabled by default.

**Comment by rlh1994** [comment]
Yeah I had tried that, then re-ran `yarn build` before `yarn start` and looking at that served locally it's still not showing any highlighting unfortunately

**Comment by rlh1994** [comment]
@stanch I've worked out what the issue with this is, the theme pulled in here:
https://github.com/snowplow/documentation/blob/8bd2d61941592df3fa3d362c2b2a851bac318264/docusaurus.config.js#L126
Doesn't have the correct rules for some yaml classes (e.g. `atrule`). Compare the dracula:
![image](https://user-images.githubusercontent.com/8260415/220697280-4a0cafac-24af-413f-bb50-7e6e7c8f8c08.png)

With the shadesOfPurple:
![image](https://user-images.githubusercontent.com/8260415/220697323-3950e80f-bb6a-47d5-8e31-29b1a2a1d9c0.png)

Solution would either be to swap to another theme that does have correct highlighting for the language, or add some custom css on top of that theme for the classes it's missing. I'm assuming the latter is your preference?

**Comment by stanch** [comment]
Oh wow. I have to say, I like the premise of “shades of purple”! It sounds very Snowplow. Could you make a PR/preview with that?
