### ISSUE TITLE
quickstart for open source on aws - iglu_server_dns_name missing protocol

### ISSUE THREAD

**Issue by piotrek660** [snowplow/documentation#207]
Hi,

I've used the default terraform modules for AWS:
1. deployed iglu server
2. deployed pipeline with using the iglu_server_dns_name output

everything works well (example & creating custom events), but the ingestion of custom don't work --> they end up with RepoFailure.

The iglu_server_dns_name output dont contain a protocol (http / https), and its also missing in the documentation.
Since it used later for the iglu resolver config, the pipeline will throw ResolutionError messages like: 
  
"errors":[{"error":"RepoFailure","message":"no protocol: sp-iglu-lb-

It would be great to at least add short info the description OR add additional input var for protocol.

Thx!

**Comment by jbeemster** [comment]
Hi @piotrek660 in the `tfvars` files included in the `aws/pipeline` directories the default value for `iglu_server_dns_name` includes the protocol for this reason (https://github.com/snowplow/quickstart-examples/blob/main/terraform/aws/pipeline/default/postgres.terraform.tfvars#L29).

I quite like the idea of adding a protocol `var` to make this explicit and then assembling it in the Terraform.  I can throw a PR together that does that pretty easily or if you have bandwidth to contribute this back that is always appreciated!

**Comment by stanch** [comment]
We now validate in Terraform that the DNS name includes the protocol.
